baseURL = 'https://michaelchan.space/'
languageCode = 'zh-cn'
title = 'Zen&Programming'
theme = 'hugo-tufte'
hasCJKLanguage = true
[taxonomies]
  category = 'categories'
  tag = 'tags'
[params]
  codeBlocksDark = false
  showSummary = true
  KaTeXVersion = '0.16.4'
  KaTeXCDN = '//cdn.jsdelivr.net/npm'
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    guessSyntax = true
[menus]
  [[menus.nav]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.nav]]
    name = '编程'
    identifier = '编程'
    pageRef = '/programming'
    weight = 20
  [[menus.nav]]
    name = '杂谈'
    identifier = '杂谈'
    pageRef = '/zen'
    weight = 30
  [[menus.nav]]
    name = '标签'
    identifier = '标签'
    pageRef = '/tags'
    weight = 40
